-- =============================================================================
-- 1. CREACIÓN DE TIPOS Y TABLAS
-- =============================================================================

CREATE TYPE sale_state AS ENUM ('Pending', 'Cancelled', 'Confirmed');

CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci INT UNIQUE,
    complement VARCHAR(2),
    razon_social VARCHAR(60) NOT NULL,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL DEFAULT 0,
    operator_id INT NOT NULL,
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    state sale_state NOT NULL DEFAULT 'Pending',
    
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT
);

CREATE TABLE cancel_reason (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INT NOT NULL,
    cancel_reason VARCHAR(100) NOT NULL,
    operator_id INT NOT NULL,
    
    CONSTRAINT fk_cancel_sales FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE sale_details (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    quantity INT NOT NULL,
    sale_id INT NOT NULL,
    subtotal NUMERIC(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    
    CONSTRAINT fk_details_sales FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE sale_report (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INT UNIQUE NOT NULL,
    operator_id INT NOT NULL,
    operator_name VARCHAR(100) NOT NULL,
    customer_id INT NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    products_summary TEXT,
    cancel_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- 2. INSERCIÓN DE DATOS DE PRUEBA (SAMPLE DATA)
-- =============================================================================

-- --- Clientes ---
-- Cliente por defecto para "Sin NIT"
INSERT INTO customer (id, ci, complement, razon_social)
VALUES (0, 0, NULL, 'SIN NIT');

-- Clientes ficticios para pruebas
INSERT INTO customer (id, ci, complement, razon_social, created_by)
VALUES 
(1, 7483920, NULL, 'PEREZ JUAN CARLOS', 10),
(2, 4930291, '1B', 'MAMANI MARIA ELENA', 10);


-- --- Ventas ---
-- Venta 1: Cliente Casual, ya cobrada (Confirmada) -> Total: 130.00
INSERT INTO sales (id, customer_id, operator_id, total_price, state, created_at)
VALUES (1, 0, 5, 130.00, 'Confirmed', CURRENT_TIMESTAMP - INTERVAL '2 hours');

-- Venta 2: Juan Perez, en caja (Pendiente) -> Total: 45.00
INSERT INTO sales (id, customer_id, operator_id, total_price, state, created_at)
VALUES (2, 1, 5, 45.00, 'Pending', CURRENT_TIMESTAMP - INTERVAL '1 hour');

-- Venta 3: Maria Elena, fue anulada (Cancelada) -> Total: 50.00
INSERT INTO sales (id, customer_id, operator_id, total_price, state, created_at)
VALUES (3, 2, 6, 50.00, 'Cancelled', CURRENT_TIMESTAMP - INTERVAL '30 minutes');


-- --- Detalles de Ventas ---
-- Detalles Venta 1 (2x Coca-Cola de 50.00 c/u + 1x Combo de 30.00 = 130.00)
INSERT INTO sale_details (product_id, unit_price, quantity, sale_id)
VALUES 
(101, 50.00, 2, 1),
(102, 30.00, 1, 1);

-- Detalles Venta 2 (3x Hamburguesas de 15.00 = 45.00)
INSERT INTO sale_details (product_id, unit_price, quantity, sale_id)
VALUES 
(103, 15.00, 3, 2);

-- Detalles Venta 3 (1x Producto X de 50.00 = 50.00)
INSERT INTO sale_details (product_id, unit_price, quantity, sale_id)
VALUES 
(101, 50.00, 1, 3);


-- --- Motivos de Cancelación ---
-- Justificación de por qué se canceló la Venta 3
INSERT INTO cancel_reason (sale_id, cancel_reason, operator_id)
VALUES (3, 'El cliente se arrepintió de la compra antes de pagar.', 6);


-- --- Histórico de Reportes (Opcional, simulando el acumulado) ---
INSERT INTO sale_report (sale_id, operator_id, operator_name, customer_id, total_price, products_summary, cancel_reason)
VALUES 
(1, 5, 'Carlos Cajero', 0, 130.00, '[{"product_id":101,"qty":2},{"product_id":102,"qty":1}]', NULL),
(3, 6, 'Ana Supervisora', 2, 50.00, '[{"product_id":101,"qty":1}]', 'El cliente se arrepintió de la compra antes de pagar.');