<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ServicioFrontend</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Dtos\**\*.cs" />
    <Compile Include="..\Authentication\**\*.cs" />
    <Compile Include="..\Validation\**\*.cs" />
  </ItemGroup>

</Project>
