<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6d874abd-2f95-40fa-956f-f68db9455607</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Application\ServicioCatalogo.Application.csproj" />
    <ProjectReference Include="Infrastructure\ServicioCatalogo.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Application\**\*.cs" />
    <Compile Remove="Domain\**\*.cs" />
    <Compile Remove="Infrastructure\**\*.cs" />
    <None Include="Application\**\*" />
    <None Include="Domain\**\*" />
    <None Include="Infrastructure\**\*" />
  </ItemGroup>

</Project>
