-- ServicioUsuarios (PostgreSQL 15+)
--
-- Ejecutar con:
-- psql -h 127.0.0.1 -p 5432 -U postgres -d mercadito_users -f schema/mercadito_postgres_usuarios_schema.sql

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(40) NOT NULL,
  email VARCHAR(120) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  creator_id INTEGER NULL,
  last_login TIMESTAMPTZ NULL,
  need_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  state VARCHAR(20) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NULL,
  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT fk_users_creator_id FOREIGN KEY (creator_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT ck_users_role CHECK (role IN ('Admin', 'Auditor', 'Operator')),
  CONSTRAINT ck_users_state CHECK (state IN ('Active', 'Inactive', 'Suspended', 'Deleted'))
);

CREATE TABLE IF NOT EXISTS user_story (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  operator_id INTEGER NOT NULL,
  previous_state VARCHAR(20) NOT NULL,
  actual_state VARCHAR(20) NOT NULL,
  disable_reason TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_user_story_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_user_story_operator_id FOREIGN KEY (operator_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT ck_user_story_previous_state CHECK (previous_state IN ('Active', 'Inactive', 'Suspended', 'Deleted')),
  CONSTRAINT ck_user_story_actual_state CHECK (actual_state IN ('Active', 'Inactive', 'Suspended', 'Deleted'))
);

CREATE TABLE IF NOT EXISTS password_reset_token (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_password_reset_token_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash),
  CONSTRAINT ck_password_reset_token_expiration CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS idx_users_state_role ON users (state, role);
CREATE INDEX IF NOT EXISTS idx_users_state_id ON users (state, id);
CREATE INDEX IF NOT EXISTS idx_user_story_user_created_at ON user_story (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_story_operator_created_at ON user_story (operator_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_lookup ON password_reset_token (user_id, used_at, expires_at DESC);
