-- ServicioEmpleados (PostgreSQL 18+)
-- Ejecutar con:
-- psql -h 127.0.0.1 -p 5412 -U postgres -d mercadito_employees -f schema/mercadito_postgres_empleados_schema.sql

CREATE TABLE IF NOT EXISTS empleados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ci BIGINT NOT NULL,
  complemento VARCHAR(2),
  complementonormalizado VARCHAR(2) GENERATED ALWAYS AS (COALESCE(complemento, '')) STORED,
  nombres VARCHAR(40) NOT NULL,
  primerapellido VARCHAR(40) NOT NULL,
  segundoapellido VARCHAR(40),
  cargo VARCHAR(20) NOT NULL,
  numerocontacto VARCHAR(40) NOT NULL,
  estado CHAR(1) NOT NULL DEFAULT 'A',
  activounico SMALLINT GENERATED ALWAYS AS (CASE WHEN estado = 'A' THEN 1 ELSE NULL::SMALLINT END) STORED,
  fecharegistro TIMESTAMP NOT NULL DEFAULT NOW(),
  ultimaactualizacion TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_empleados_ci_rango CHECK (ci BETWEEN 1000000 AND 99999999),
  CONSTRAINT chk_empleados_nombres_no_vacio CHECK (BTRIM(nombres) <> ''),
  CONSTRAINT chk_empleados_primer_apellido_no_vacio CHECK (BTRIM(primerapellido) <> ''),
  CONSTRAINT chk_empleados_contacto_no_vacio CHECK (BTRIM(numerocontacto) <> ''),
  CONSTRAINT chk_empleados_contacto_formato CHECK (numerocontacto ~ '^[0-9]{8}$'),
  CONSTRAINT chk_empleados_cargo CHECK (cargo IN ('Cajero', 'Inventario')),
  CONSTRAINT chk_empleados_estado CHECK (estado IN ('A', 'I')),
  CONSTRAINT chk_empleados_complemento_formato CHECK (complemento IS NULL OR complemento ~ '^[0-9][A-Z]$')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_empleados_activos_ci_complemento
  ON empleados (ci, complementonormalizado, activounico);

CREATE INDEX IF NOT EXISTS empleados_idx_estado_apellidos_nombres
  ON empleados (estado, primerapellido, segundoapellido, nombres, id);

CREATE INDEX IF NOT EXISTS empleados_idx_estado_ci
  ON empleados (estado, ci, id);

CREATE OR REPLACE FUNCTION set_ultimaactualizacion_empleados()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.ultimaactualizacion = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_set_ultimaactualizacion_empleados ON empleados;
CREATE TRIGGER trg_set_ultimaactualizacion_empleados
BEFORE UPDATE ON empleados
FOR EACH ROW
EXECUTE FUNCTION set_ultimaactualizacion_empleados();
