-- ServicioDeVentas (PostgreSQL 15+)
--
-- Ejecutar con:
-- psql -h 127.0.0.1 -p 5452 -U postgres -d mercadito_db_sales -f schema/mercadito_postgres_ventas_schema.sql

-- =============================================================================
-- 1. CREACIÓN DE TIPOS Y TABLAS
-- =============================================================================

CREATE TYPE sale_state AS ENUM ('Pending', 'Cancelled', 'Confirmed');

CREATE TABLE customer (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci INT UNIQUE,
    complement VARCHAR(2),
    ci_nit VARCHAR(20) UNIQUE,
    razon_social VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(100),
    address VARCHAR(150),
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20),
    customer_id INT NOT NULL DEFAULT 0,
    operator_id INT NOT NULL,
    operator_username VARCHAR(80),
    channel VARCHAR(30) NOT NULL DEFAULT 'Mostrador',
    payment_method VARCHAR(30) NOT NULL DEFAULT 'Efectivo',
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    state sale_state NOT NULL DEFAULT 'Confirmed',
    cancelled_by_user_id BIGINT,
    cancelled_by_username VARCHAR(80),
    cancelled_at TIMESTAMP,

    CONSTRAINT uq_sales_code UNIQUE (code),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE RESTRICT
);

CREATE TABLE cancel_reason (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INT NOT NULL,
    cancel_reason VARCHAR(200) NOT NULL,
    operator_id INT NOT NULL,
    operator_username VARCHAR(80),
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cancel_sales FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE sale_details (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT NOT NULL,
    product_name_snapshot VARCHAR(150),
    lot_code VARCHAR(40),
    unit_price NUMERIC(12,2) NOT NULL,
    quantity INT NOT NULL,
    sale_id INT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    updated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    subtotal NUMERIC(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,

    CONSTRAINT fk_details_sales FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE
);

CREATE TABLE sales_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INT,
    action VARCHAR(20) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    actor_username VARCHAR(80) NOT NULL,
    previous_state sale_state,
    current_state sale_state,
    previous_data JSONB,
    new_data JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sales_audit_log_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL
);

CREATE TABLE sales_saga_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INT,
    step VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    actor_username VARCHAR(80) NOT NULL,
    product_id INT,
    quantity INT,
    error_message VARCHAR(300),
    payload JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sales_saga_log_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL
);

CREATE INDEX idx_sales_created_at ON sales (created_at DESC);
CREATE INDEX idx_sales_state_created_at ON sales (state, created_at DESC);
CREATE INDEX idx_sales_payment_method ON sales (payment_method);
CREATE INDEX idx_sale_details_sale_id ON sale_details (sale_id);
CREATE INDEX idx_sales_audit_log_sale_id ON sales_audit_log (sale_id, created_at DESC);
CREATE INDEX idx_sales_saga_log_sale_id ON sales_saga_log (sale_id, created_at DESC);
CREATE INDEX idx_sales_saga_log_step_status ON sales_saga_log (step, status, created_at DESC);
