CREATE TABLE sale_report (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INT UNIQUE NOT NULL,
    operator_id INT NOT NULL,
    operator_name VARCHAR(100) NOT NULL,
    customer_id INT NOT NULL,
    total_price NUMERIC(12,2) NOT NULL,
    products_summary TEXT,
    cancel_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- --- Histórico de Reportes (Opcional, simulando el acumulado) ---
INSERT INTO sale_report (sale_id, operator_id, operator_name, customer_id, total_price, products_summary, cancel_reason)
VALUES 
(1, 5, 'Carlos Cajero', 0, 130.00, '[{"product_id":101,"qty":2},{"product_id":102,"qty":1}]', NULL),
(3, 6, 'Ana Supervisora', 2, 50.00, '[{"product_id":101,"qty":1}]', 'El cliente se arrepintió de la compra antes de pagar.');