<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0e750f5e-0f3a-4cb8-8f03-f7974c57fd08</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Application\ServicioEmpleados.Application.csproj" />
    <ProjectReference Include="Infrastructure\ServicioEmpleados.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Application\**\*.cs" />
    <Compile Remove="Domain\**\*.cs" />
    <Compile Remove="Infrastructure\**\*.cs" />
    <None Include="Application\**\*" />
    <None Include="Domain\**\*" />
    <None Include="Infrastructure\**\*" />
  </ItemGroup>

</Project>
